export const GOT_ALL_ARTICLES = 'GOT_ALL_ARTICLES';
export const GOT_MY_ARTICLES = 'GOT_MY_ARTICLES';
export const GOT_SINGLE_ARTICLE = 'GOT_SINGLE_ARTICLE';

export const GOT_ALL_FLOWS = 'GOT_ALL_FLOWS';
export const GOT_MY_FLOWS = 'GOT_MY_FLOWS';
export const GOT_SINGLE_FLOW = 'GOT_SINGLE_FLOW';

export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGOUT_USER = 'LOGOUT_USER';